version: '3.9'

services:
  transinterdigital:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/app
    environment:
      - GO111MODULE=on
    stdin_open: true
    tty: true

  postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      ports:
        - 5432:5432
      volumes:
        - ./data:/var/lib/postgresql/data
      restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8080:80
    restart: always
